apiVersion: v1
kind: Service
metadata:
  name: svc-maria
  namespace: database  
spec:
  selector:
    app: mariadb
  ports:
    - port: 3306
      targetPort: 3306


---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: database
  name: mariadb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb
          ports:
            - containerPort: 3306
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-root-secret
                  key: MARIADB-ROOT-PASSWORD
            - name: MARIADB_USER
              valueFrom:
                secretKeyRef:
                  name: mariadb-user-secret
                  key: MARIADB_USER
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-user-secret
                  key: MARIADB_PASSWORD
          volumeMounts:
              - name: mariadb
                mountPath: /var/lib/mysql
      volumes:
        - name: mariadb
          awsElasticBlockStore:
        # Enter the volume ID below
            volumeID: vol-094aba4fa72929c21
            fsType: ext4

