apiVersion: v1
kind: PersistentVolume
metadata:
  name: aws-pvc
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  storageClassName: gp2
  persistentVolumeReclaimPolicy: Retain
  awsElasticBlockStore:
    volumeID: vol-094aba4fa72929c21
    fsType: ext4
